spring:
  datasource:
    url: jdbc:postgresql://localhost5432/postgres
    username: postgres
    password: changemeinprod!
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: off
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:9090/realms/event-ticket-platform